github: @FabianaCampanari
['https://github.com/FabianaCampanari',
'https://github.com/FabianaCampanari/SkyWalkerConverter']
open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/top-trumps']
