  
                    
github: [FabianaCampanari, Quantum-Software-Development]
github: ['https://github.com/FabianaCampanari', 'https://github.com/Quantum-Software-Development']


open_collective: [FabianaCampanari. @quantum-software-development]
open_collective: ['https://opencollective.com/fabianacampanari', 'https://opencollective.com/quantum-software-development']


stripre_express: FabianaCampanari  
stripre_express: ['https://stripe.com/docs/financial-services']


github_sponsors: ['https://github.com/sponsors/FabianaCampanari', 'https://github.com/sponsors/Quantum-Software-Development']


embedded_sponsor_button:
<iframe src="https://github.com/sponsors/FabianaCampanari/button" title="Sponsor FabianaCampanari" height="32" width="114" style="border: 0; border-radius: 6px;"></iframe>


embedded_sponsor_card:
<iframe src="https://github.com/sponsors/FabianaCampanari/card" title="Sponsor FabianaCampanari" height="225" width="600" style="border: 0;"></iframe>

