name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Auto Sign
      uses: FabianaCampanari/auto-sign@v1.2.0
      with:
        commit_message: "Auto sign commit"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
